# Site settings
title: Pangolin
email: stevenlovegrove@gmail.com
description: Pangolin C++ Library Homepage
url: "https://stevenlovegrove.github.io"
baseurl: "/Pangolin"
twitter_username: stevenjl
github_username:  stevenlovegrove

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
logo: https://raw.githubusercontent.com/stevenlovegrove/Pangolin/master/tools/VideoViewer/application-x-pango.svg
show_downloads: "false"

plugins:
  - jekyll-relative-links
