# Site settings
title: Pangolin
email: stevenlovegrove@gmail.com
description: > 
  Pangolin C++ Library Homepage
baseurl: "/Pangolin"
url: "https://stevenlovegrove.github.io/Pangolin"
twitter_username: stevenjl
github_username:  stevenlovegrove

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
logo: https://raw.githubusercontent.com/stevenlovegrove/Pangolin/master/tools/VideoViewer/application-x-pango.svg
show_downloads: "false"
gems:
  - jekyll-feed
